---
title: "benchmarking kriging vs tuned kriging"
author: "Thomas Goossens"
date: "12/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all()
```


## Load the libraries

```{r libraries,results='hide'}
# loading mlr & agrometeoR
library(agrometeoR)
library(mlr)
library(parallelMap)
```


## create the tasks
```{r tasks, results='hide', message=FALSE}
# create the task
tasks = makeTask(dataset = makeDataset(dfrom = "2017-03-04T00:00:00Z", dto = "2017-03-04T23:00:00Z", sensor = "tsa")$output$value, target = "tsa")

data("learners")
bmr.learners = list(
    learners$lrn.gstat.ked)


      bmr = mlr::benchmark(
        learners = bmr.learners,
        tasks = tasks$output$value,
        resamplings = mlr::makeResampleDesc("LOO"),
        measures = rmse,
        keep.pred = FALSE,
        models = FALSE)
```

## benchmark some learners on a subset of these tasks
```{r benchmark, message=FALSE, warning=FALSE, results='hide'}
# loading the learners preconfigured with the package

bmr.1core = makeBenchmark(
  tasks = tasks$output$value[1:3],
  learners = c(
    learners$lrn.gstat.ked,
    learners$lrn.gstat.ked.tuning,
    learners$lrn.gstat.ok,
    learners$lrn.gstat.ok.tuning))
```



## vizualize performance 
```{r}
plotBMRBoxplots(bmr.1core$output$value$bmr, pretty.names = FALSE)
plotBMRSummary(bmr.1core$output$value$bmr, pretty.names = FALSE)
```

## Check if parallelization improves computing speed

Let's re-run the same benchmark but on 4 cores this time

```{r parallel, message=FALSE, warning=FALSE, results ='hide' }
# with parallel computing
bmr.4cores = makeBenchmark(tasks = tasks$output$value[1:3], learners = learners, cpus = 4)
```

We can see that we have an improvement of the computation time of a factor of `r bmr.1core$output$value$exectime/bmr.4cores$output$value$exectime`

