---
title: "Last improvments"
author: "Thomas Goossens"
date: "2/28/2019"
output: html_document
---

* EC (explanations) ==> db : une table dédiée + champs encodés
* TODO : create a new table for batch of benchamrks experiments + best EC
* package objects to manage : learners
* Package R doit être la plus généraliste possible et donc les questions d'EC doivent être côté python qui est plus dédié à popote interne
* la question se posait de savoir si les EC devaient être construites dans R ou pas : non car popte interne
* question de généralisation des fonctions et objets : modularité en interne : stations, learners (via mlr et appel api DB)
* Features en grid : statiques vs dynamiques : sortir en une fonction qui alimente le grid en variables explicatives statiques + list de features en params
* tests unitaires : vérifs de stations à une certaine date
* metadata pour chaque px et pour chaque heure (deux tables différentes). Les ùetadata par couche fonctionnent déjà dans la db : heure, senseur = repère. best EC, summary spatial, indicateurs Perfs, stations retenues, stations exclues, liste des EC parmi lesquelles la meilleure
* table pour les résidus par stations
* retour stations ignorées = seulement les exclues parmi les choisies
* attention FLAG donnée insérée depuis station voisine ou non => côté python et JP
* makeDataset va devoir être branchée en direct sur nouvelle API de récup de données des stations OK + incaTO
* fct pour liveGrids features
