---
title: "Networks Intercomparison"
author: "Thomas Goossens"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all()
```

## Load the libraries

```{r libraries,results='hide'}
# loading mlr & agrometeoR
library(agrometeoR)
library(mlr)
library(parallelMap)
library(microbenchmark)
```


## create the tasks
```{r tasks, results='hide'}
# create the task
tasks = makeTasks(dataset = makeDataset(dfrom = "2017-03-04T00:00:00Z", dto = "2017-03-04T23:00:00Z", sensor = "tsa"), target = "tsa")

```

## benchmark some learners on a subset of these tasks
```{r benchmark, message=FALSE, warning=FALSE, results='hide'}
# loading the learners preconfigured with the package
data("learners")
bmr = makeBenchmark(tasks = tasks[1:3], learners = learners)
```

## vizualize performance 
```{r}
plotBMRBoxplots(bmr$bmr, pretty.names = FALSE)
plotBMRSummary(bmr$bmr, pretty.names = FALSE)
```

## Check if parallelization improves computing speed

```{r parallel, message=FALSE, warning=FALSE, results ='hide' }
# with parallel computing
parallel = microbenchmark(makeBenchmark(tasks = tasks[1:3], learners = learners, parallel = TRUE), times = 1)
single = microbenchmark(makeBenchmark(tasks = tasks[1:3], learners = learners, parallel = FALSE), times = 1)
```

```{r}
parallel$time < single$time
parallel$time
single$time
```

