---
title: "A simple spatialization example using agrometeoR"
author: "Thomas Goossens"
date: "11/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all()
library(mlr)
```

## Load the libraries

```{r libraries, eval=FALSE}
# loading mlr & agrometeoR
library(mlr)
library(agrometeoR)
```


## Create the machine learning task for a specific hour
*Check the default values of the params in the references file to make sure you understand what is constructed* 
```{r task, message=FALSE, warning=FALSE, paged.print=TRUE}
# create the dataset
myDataset = (makeDataset(dfrom = "2017-03-04T15:00:00Z", dto = "2017-03-04T15:00:00Z", sensor = "tsa"))$output$value
# create the task
myTask = makeTask(dataset = myDataset[[1]], target = "tsa")
# what are the variables ? 
colnames(mlr::getTaskData(myTask$output$value))
# what data do we have ? 
head(getTaskData(myTask$output$value))
```

## Train a learner

```{r train, message=FALSE, warning=FALSE, paged.print=TRUE}
# instantiate a multiple linear regression learner and specify that it must also provide se of preds
myLearner = mlr::makeLearner("regr.lm", id = "multipleLinearReg", predict.type = "se" )
# create the model by training the learner and also benchmark the learner with a LOO
myModel = makeModel(task = myTask$output$value, learner = myLearner)
# what are the model performances ? 
myModel$output$value$perfs$agg
# what about the residuals ? 
plot(x =  getTaskData(myTask$output$value)[["tsa"]], myModel$output$value$residuals[[1]])
```

## Spatialize using the trained a learner

```{r spatializeconfig, include=FALSE}
# trick to avoir overwriting error with st_write - https://github.com/r-spatial/sf/issues/274
files = list.files()
if (!is.null(paste0(myTask$output$value$task.desc$id, ".geojson" %in% files))) {
  file.remove(paste0(myTask$output$value$task.desc$id, ".geojson"))
}
```

```{r spatialize, message=FALSE, warning=FALSE, paged.print=TRUE}
# produce the spatialized geojson
spatialized = makeSpatialization(model = myModel$output$value$trained)
# read it
head(spatialized$output$value)
```

## Map the results
```{r}
# make it a spatial object
spatialized.sf = sf::st_as_sf(spatialized$output$value, coords = c("X","Y"))
# map it ! 
plot(spatialized.sf)
```

