---
title: "version 0.0.0.900 - first dev version"
author: "Thomas Goossens"
date: "11/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This version implements the ZEPP method : multiple linear regression based and X, Y and alt.

To understand the settings described belo, please read the mlr doc : https://mlr.mlr-org.com

## implemented learners 

### multiple linear regressions

learner = regr.lm
tuning = FALSE
auto-tuning = FALSE
feature-filtering = FALSE
feature-selection = FALSE

```r
learner = mlr::makeLearner(cl = "regr.lm", id = "multiple-linear-reg", predict.type = "se")
```

## implemented features

## example
```{r setup, include=FALSE}
library(agrometeoR)
# create the regression task for a specific hour for a specific sensor
task = makeTask(date = "2017-05-24", sensor = "tsa")
# create the model based on the task
model = makeModel(
  task = task$task,
  learner = mlr::makeLearner(cl = "regr.lm", id = "multiple-linear-reg", predict.type = "se"))
# create the geojson spatialized file
makeSpatialization(
  model = model$model,
  name = model$model$task.desc$id,
  path = getwd(),
  )
```



